language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
    - develop
    - release
bundler_args: --without development
script:
  - cp test/support/test_config.yml.travis-ci test/support/test_config.yml
  - bundle exec rake
