require_relative '../../../../test_helper'

include RedStack::Identity::Controllers

describe 'RedStack::Identity::Controllers::ProjectsController' do

  # before do
  #   @os = new_openstack_session
  #   @os.authenticate username: 'validuser', password: '123qwe'
  #   @projects = ProjectsController.new(session: @os)
  # end
  # 
  # it 'retrieves projects of the currently logged in user' do
  #   projects = @projects.find
  #   
  #   projects.must_equal @projects
  #   projects.length.wont_be_nil
  # end
  # 
  # it 'implements the first method' do
  #   @projects.must_respond_to :first
  # end
  # 
  # it 'creates a new project' do
  #   @os.authenticate username: 'admin', password: 'password'
  #   attributes = {
  #     name: 'AHFZSYVH',
  #     description: 'This is a project generated by RedStack',
  #     enabled: true
  #   }
  #   
  #   project = @projects.create attributes
  #   project.must_be_instance_of ProjectController
  #   @projects.items.detect{|p| p['id'] == project['id']}.wont_be_nil
  #   project['name'].must_equal attributes[:name]
  #   project['description'].must_equal attributes[:description]
  #   project['enabled'].must_equal attributes[:enabled]
  # end
     
end