require_relative '../../../../test_helper'

include RedStack::Models::Identity

describe 'RedStack::Models::Identity:Project' do

  before do
    @os = new_openstack_session
    @os.authenticate username: 'validuser', password: '123qwe'
  end
  
  it 'retrieves projects' do
    projects = Project.find(token: @os.access['default']['token']['id'], connection: @os.connection)
    
    projects.must_be_instance_of Array
    projects.length.wont_be_nil
  end

  # DUPLICATE
  # it 'creates a project' do
  #   @os = RedStack::Session.new(host: 'http://devstack:5000', api_version: 'v2.0', stub_openstack: true)
  #   @os.authenticate username: 'admin', password: 'password'
  #   @os.request_admin_access
  #   service_endpoint = @os.access['admin']['serviceCatalog']
  #                      .detect{ |s|s['type']=='identity' }['endpoints'][0]['adminURL']
  #   connection = @os.connection.dup
  #   connection.url_prefix = service_endpoint
  #   
  #   attributes = {
  #     name:         'REDSTACK' + (0...8).map{(65+rand(26)).chr}.join,
  #     description:  'This is a project generated by RedStack',
  #     enabled:      true
  #   }
  # 
  #   project = Project.create(
  #               attributes: attributes, 
  #               token: @os.access['admin']['token']['id'],
  #               connection: connection
  #             )
  #   
  #   project.must_be_instance_of Project
  #   project['name'].must_equal attributes[:name]
  #   project['description'].must_equal attributes[:description]
  #   project['enabled'].must_equal attributes[:enabled]
  # end
       
end