require_relative '../../../../test_helper'

include RedStack::Controllers::Identity

describe 'RedStack::Controllers::Identity::ProjectsController' do

  before do
    @os = RedStack::Session.new(host: 'http://devstack:5000', api_version: 'v2.0', stub_openstack: true)
    @os.authenticate username: 'validuser', password: '123qwe'
    @projects = ProjectsController.new(session: @os)
  end

  it 'retrieves projects of the currently logged in user' do
    projects = @projects.find
    
    projects.must_equal @projects
    projects.length.wont_be_nil
  end
  
  it 'implements the first method' do
    @projects.must_respond_to :first
  end
  
  it 'creates a new project' do
    new_project = {
      name: (0...8).map{(65+rand(26)).chr}.join,
      description: 'This is a project generated by RedStack',
      enabled: true
    }
    
    project = @projects.create new_project
    project.must_be_instance_of ProjectController
    @projects.find(id: project.id).length.must_equal 1
  end
     
end